
BLENDER="C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
DIST=../dist

all : \
	$(DIST)/burnin.pnct \
	$(DIST)/burnin.scene \

$(DIST)/burnin.scene : burnin.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "burnin.blend:Main" "$(DIST)/burnin.scene"

$(DIST)/burnin.pnct : burnin.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "burnin.blend:Main" "$(DIST)/burnin.pnct" 